# Generated by Django 3.2 on 2022-01-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
                ('category_info', models.CharField(max_length=280)),
                ('category_slug', models.CharField(default='default', max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
