# Generated by Django 3.2 on 2022-01-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.CharField(default='default_post', max_length=80),
        ),
    ]
