# Generated by Django 3.2 on 2022-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='img',
            field=models.ImageField(default='', upload_to='blog/static/img/categories'),
        ),
    ]
